@extends('layouts.main')
@php $amen=json_decode($project->amenities??'[]',true)?:[];$spec=json_decode($project->specifications??'{}',true)?:[];$near=json_decode($project->nearby_places??'{}',true)?:[]; @endphp
@section('title','Review Builder Project')
@section('page-title')<div class="page-title"><h4>Review Project #{{ $project->id }}</h4><div style="font-size:11px;color:#94a3b8">{{ $project->reference_no }}</div></div>@endsection
@section('content')
<div style="padding:16px 20px 40px;max-width:1180px"><div class="row g-3"><div class="col-lg-8">
<div class="card p-3 mb-3"><h4>{{ $project->title }}</h4><div class="text-muted">{{ $project->company_name ?: $project->owner_name }} · {{ $project->city }}, {{ $project->state }}</div><hr><p>{{ $project->description }}</p><div class="row g-2 small"><div class="col-md-4"><strong>Segment</strong><br>{{ ucfirst($project->project_segment) }}</div><div class="col-md-4"><strong>Subtype</strong><br>{{ $project->project_subtype }}</div><div class="col-md-4"><strong>Project Status</strong><br>{{ $project->type }}</div><div class="col-md-4"><strong>RERA</strong><br>{{ $project->rera_number ?: '—' }}</div><div class="col-md-4"><strong>Possession</strong><br>{{ $project->possession_date ?: '—' }}</div><div class="col-md-4"><strong>Units</strong><br>{{ $project->available_units ?: '—' }}/{{ $project->total_units ?: '—' }}</div></div></div>
<div class="card p-3 mb-3"><h5>Unit Configurations</h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Configuration</th><th>Carpet</th><th>Built-up</th><th>Start Price</th><th>Max Price</th><th>Available</th></tr></thead><tbody>@foreach($units as $u)<tr><td>{{ $u->configuration }}</td><td>{{ $u->carpet_area }}</td><td>{{ $u->built_up_area }}</td><td>₹{{ number_format($u->starting_price) }}</td><td>₹{{ number_format($u->maximum_price) }}</td><td>{{ $u->available_units }}</td></tr>@endforeach</tbody></table></div></div>
@if(count($amen))<div class="card p-3 mb-3"><h5>Amenities</h5>@foreach($amen as $a)<span class="badge bg-light text-dark me-1 mb-1">{{ $a }}</span>@endforeach</div>@endif
<div class="card p-3 mb-3"><h5>Gallery</h5><div style="display:flex;gap:8px;flex-wrap:wrap">@foreach($images as $img)<img src="{{ asset('images/builder_projects/'.$project->id.'/'.$img->image) }}" style="width:145px;height:100px;object-fit:cover;border-radius:8px">@endforeach</div></div>
<div class="card p-3"><h5>Floor Plans</h5>@forelse($floorPlans as $f)<a target="_blank" href="{{ asset('images/builder_projects/'.$project->id.'/'.$f->file_name) }}">{{ $f->title }}</a><br>@empty<span class="text-muted">No floor plans uploaded.</span>@endforelse</div>
</div><div class="col-lg-4"><div class="card p-3" style="position:sticky;top:90px"><h5>Builder / Developer</h5><p>{{ $project->company_name ?: $project->owner_name }}<br>{{ $project->owner_email }}<br>{{ $project->owner_mobile }}<br>Promoter RERA: {{ $project->rera_promoter_number ?: '—' }}</p>
@if($project->admin_remarks)<div class="alert alert-warning small">{{ $project->admin_remarks }}</div>@endif
@if($project->request_status==='pending')<form method="POST" action="{{ url('/builder-project-approvals/'.$project->id.'/status') }}">@csrf<textarea class="form-control mb-2" name="remarks" placeholder="Remarks required for Request Changes / Reject"></textarea><button class="btn btn-success w-100 mb-2" name="status" value="approved">Approve & Publish</button><button class="btn btn-warning w-100 mb-2" name="status" value="changes_requested">Request Changes</button><button class="btn btn-danger w-100" name="status" value="rejected">Reject</button></form>@elseif($project->request_status==='approved')<div class="alert alert-success mb-0">Approved and active on frontend.</div>@elseif($project->request_status==='changes_requested')<div class="alert alert-warning mb-0">Waiting for Builder to update and resubmit.</div>@endif
</div></div></div></div>
@endsection