@extends('frontend.layouts.app')
@section('title','New Projects — BigWein')
@push('styles')
<style>
.pjhero{background:linear-gradient(135deg,#111629,#2f2039);padding:42px 0;color:#fff}.pjhero h1{font-size:34px;font-weight:800}.pjhero p{color:#cbd5e1;font-size:12px}.pjfilter{background:#fff;border-bottom:1px solid #e5e7eb;padding:13px 0}.pjfilter form{display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:8px}.pjfilter input,.pjfilter select{border:1px solid #dce3eb;border-radius:9px;padding:10px;font-size:11px}.pjfilter button{border:0;background:#e5343a;color:#fff;border-radius:9px;padding:0 18px;font-weight:800}
.pjbody{background:#f7f9fc;padding:28px 0 55px}.pjgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.pjcard{background:#fff;border:1px solid #e6eaf1;border-radius:16px;overflow:hidden;text-decoration:none;color:inherit;transition:.2s}.pjcard:hover{transform:translateY(-3px);box-shadow:0 12px 30px rgba(15,23,42,.08)}.pjimg{height:205px;background:#eef2f7}.pjimg img{width:100%;height:100%;object-fit:cover}.pjinfo{padding:15px}.pjt{font-size:16px;font-weight:800;color:#172033}.pjloc{font-size:10px;color:#64748b;margin-top:5px}.pjprice{font-size:17px;color:#e5343a;font-weight:800;margin-top:10px}.pjchips{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.pjchip{font-size:9px;background:#f8fafc;border:1px solid #e5e7eb;padding:5px 7px;border-radius:999px}.pjbuilder{font-size:10px;color:#64748b;border-top:1px solid #f0f2f5;margin-top:12px;padding-top:10px}
@media(max-width:900px){.pjgrid{grid-template-columns:repeat(2,1fr)}}@media(max-width:620px){.pjgrid{grid-template-columns:1fr}.pjfilter form{grid-template-columns:1fr}.pjfilter button{padding:10px}}
</style>
@endpush
@section('content')
<section class="pjhero"><div class="container"><h1>Builder Projects</h1><p>{{ $projects->total() }} approved projects from verified Builders & Developers</p></div></section>
<div class="pjfilter"><div class="container"><form method="GET"><select name="city"><option value="">All Cities</option>@foreach($cities as $city)<option {{ request('city')===$city?'selected':'' }}>{{ $city }}</option>@endforeach</select><select name="segment"><option value="">All Segments</option>@foreach(['residential'=>'Residential','commercial'=>'Commercial','mixed'=>'Mixed Use','plotted'=>'Plotted'] as $k=>$v)<option value="{{ $k }}" {{ request('segment')===$k?'selected':'' }}>{{ $v }}</option>@endforeach</select><select name="type"><option value="">Any Status</option>@foreach(['Upcoming','New Launch','Under Construction','Ready to Move'] as $v)<option {{ request('type')===$v?'selected':'' }}>{{ $v }}</option>@endforeach</select><button>Search Projects</button></form></div></div>
<section class="pjbody"><div class="container">@if($projects->count())<div class="pjgrid">@foreach($projects as $p)@php $img=$p->image?asset('images/'.trim(config('global.PROJECT_IMG_PATH','project/'),'/').'/'.$p->image):null;@endphp<a class="pjcard" href="{{ url('/project/'.$p->slug_id) }}"><div class="pjimg">@if($img)<img src="{{ $img }}" alt="{{ $p->title }}">@endif</div><div class="pjinfo"><div class="pjt">{{ $p->title }}</div><div class="pjloc"><i class="fa-solid fa-location-dot"></i> {{ $p->location }}, {{ $p->city }}, {{ $p->state }}</div><div class="pjprice">@if($p->min_price)Starting ₹{{ number_format($p->min_price) }}@else Price on Request @endif</div><div class="pjchips">@if($p->configurations)<span class="pjchip">{{ $p->configurations }}</span>@endif<span class="pjchip">{{ $p->type }}</span>@if($p->rera_number)<span class="pjchip">RERA ✓</span>@endif</div><div class="pjbuilder"><strong>{{ $p->company_name ?: $p->owner_name ?: 'BigWein Project' }}</strong> @if($p->possession_date) · Possession {{ \Carbon\Carbon::parse($p->possession_date)->format('M Y') }} @endif</div></div></a>@endforeach</div><div style="margin-top:22px">{{ $projects->links() }}</div>@else<div style="background:#fff;padding:50px;border-radius:14px;text-align:center;color:#94a3b8">No projects match your search.</div>@endif</div></section>
@endsection